name: eclipse
base: core26

title: Eclipse IDE
license: EPL-2.0
version: 2026-06
summary: Extensible Tool Platform and Java IDE
description:
  The Eclipse Java IDE is extensible and also features environments for
  C/C++, JavaScript and others that can be further extended by plug-ins.
contact:
  - https://www.eclipse.org/org/foundation/contact.php
donation:
  - https://www.eclipse.org/sponsor/ide/
issues:
  - https://github.com/eclipse-linuxtools/eclipse-ide-snap/issues
  - https://github.com/eclipse-platform/#reporting-issues
source-code:
  - https://github.com/eclipse-platform
website:
  - https://eclipseide.org/

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:

apps:
  eclipse:
    command: bin/eclipse-wrapper

parts:
  eclipse:
    plugin: dump
    source-type: tar
    source:
      - on amd64: https://download.eclipse.org/technology/epp/downloads/release/${SNAPCRAFT_PROJECT_VERSION}/R/eclipse-java-${SNAPCRAFT_PROJECT_VERSION}-R-linux-gtk-x86_64.tar.gz
      - on arm64: https://download.eclipse.org/technology/epp/downloads/release/${SNAPCRAFT_PROJECT_VERSION}/R/eclipse-java-${SNAPCRAFT_PROJECT_VERSION}-R-linux-gtk-aarch64.tar.gz
    build-attributes:
      - no-patchelf
    override-build: |
      cp -a "$CRAFT_PART_SRC"/. "$CRAFT_PART_INSTALL"
      find $CRAFT_PART_INSTALL/ -type d -exec chmod 755 {} \;
      find $CRAFT_PART_INSTALL/ -type f -exec chmod 644 {} \;
      find $CRAFT_PART_INSTALL/ -type f -exec chmod +x {} \;
    stage-packages:
      - libffi8
      - libfreetype6
      - libpng16-16t64
      - libgdk-pixbuf-2.0-0
      - librsvg2-common
      - libsecret-1-0
      - libasound2
      - libxi6
      - libxrender1
      - libxtst6
    override-prime: |
      craftctl default
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/aix*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/darwin*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/dragonflybsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/freebsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/openbsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/sunos*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/win32*/
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      eclipse: bin/eclipse-wrapper

lint:
  ignore:
  - classic
  - library:
    - plugins/**/*.so
    - usr/lib/**/*.so*
